### ISSUE TITLE
Error after trying to Build DAG of jobs

### ISSUE THREAD

**Issue by jesszha** [WatsonLab/sm_assemblies#2]
Hello!

I followed the pipeline and downloaded all dependencies and ran the pipeline using the command specified: snakemake --use-conda, however, I seem to be stuck on a KeyError on the step that should be outputting blat_nanopore.tsv. Here is the step and error I run into: 

`
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	2	blat
	1	combine_lists
	6	get_list
	6	report
	6	splign
	1	unique_tid
	23

[Mon Feb 11 15:20:20 2019]
rule report:
    input: blat_nanopore.psl, protein_coding_exons.filtered.fasta
    output: blat_nanopore.tsv
    jobid: 22
    wildcards: id=nanopore

Job counts:
	count	jobs
	1	report
	1
[Mon Feb 11 15:20:36 2019]
Error in rule report:
    jobid: 0
    output: blat_nanopore.tsv

RuleException:
KeyError in line 139 of /projects/btl_scratch/jzhang/ntedit/longread_correction/sm_assemblies/Snakefile:
'ENSG00000168036|ENST00000643541;ENST00000645210;ENST00000646381;ENST00000405570;ENST00000642248;ENST00000433400;ENST00000642992;ENST00000431914;ENST00000642836;ENST00000349496;ENST00000396185;ENST00000642986;ENST00000644678;ENST00000396183;ENST00000643031;ENST00000645982;ENST00000453024;ENST00000647264;ENST00000645900;ENST00000646174;ENST00000643992;ENST00000647390;ENST00000642886;ENST00000644138;ENST00000645276;ENST00000642426;ENST00000646116;ENST00000644873;ENST00000644867;ENST00000646725;ENST00000645493'
  File "/projects/btl_scratch/jzhang/ntedit/longread_correction/sm_assemblies/Snakefile", line 139, in __rule_report
  File "/home/jezhang/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /projects/btl_scratch/jzhang/ntedit/longread_correction/sm_assemblies/.snakemake/log/2019-02-11T152013.346673.snakemake.log
`

**Comment by matrs** [comment]
I've also found this problem trying only with coding sequences from one chromosome.
in the `report` rule, two input files are used. One,  the `psl` file, which comes from  `blat`,  has lines that don't include all the  ids from the fasta file ( the  `> description/ids` lines from `protein_coding_exons.filtered.fasta`).

For example, my code using only chromosome 18, you can see this:
```python
KeyError                                  Traceback (most recent call last)
<ipython-input-175-474c09a32604> in <module>
     24             continue
     25     top_hits[arr[0]] = 1
---> 26     print("%s\t%s\t%s\t%s\t%s\t%s" % (arr[0], seq_length[arr[0]], arr[2], arr[3], arr[4], arr[5]), file=f)
     27 
     28 f.close()

KeyError: 'ENSG00000130856|ENST00000253159|ENSE00003680587;ENSE00003461570;ENSE00001299490;ENSE00001280732;ENSE00003521981;ENSE00003626243;ENSE00001179496;ENSE00003458277;ENSE00003471855;ENSE00001280886;ENSE00001300789;ENSE00001280745;ENSE00001280714;ENSE00000894937;ENSE00001349209;ENSE00001280898;ENSE00001309083;ENSE00003609826;ENSE00003569780;ENSE00001280757;ENSE00003690442;ENSE00001330668;ENSE00000894918;ENSE00001280724;ENSE00001326724;ENSE00001179502;ENSE00003591609;ENSE00000894939;ENSE00001280856;ENSE00001383033'
```
When you take that key and check the `protein_coding_exons.filtered.fasta` you get:
```bash
$ egrep -F
'ENSG00000130856|ENST00000253159|ENSE00003680587;ENSE00003461570;ENSE00001299490;
ENSE00001280732;ENSE00003521981;ENSE00003626243;ENSE00001179496;ENSE00003458277;
ENSE00003471855;ENSE00001280886;ENSE00001300789;ENSE00001280745;ENSE00001280714;
ENSE00000894937;ENSE00001349209;ENSE00001280898;ENSE00001309083;ENSE00003609826;
ENSE00003569780;ENSE00001280757;ENSE00003690442;ENSE00001330668;ENSE00000894918;
ENSE00001280724;ENSE00001326724;ENSE00001179502;ENSE00003591609;ENSE00000894939;
ENSE00001280856;ENSE00001383033' \
protein_exons_size_filtered_chr18.fasta

331:>ENSG00000130856|ENST00000253159|ENSE00003680587;ENSE00003461570;
ENSE00001299490;ENSE00001280732;ENSE00003521981;ENSE00003626243;ENSE00001179496;
ENSE00003458277;ENSE00003471855;ENSE00001280886;ENSE00001300789;ENSE00001280745;
ENSE00001280714;ENSE00000894937;ENSE00001349209;ENSE00001280898;ENSE00001309083;
ENSE00003609826;ENSE00003569780;ENSE00001280757;ENSE00003690442;ENSE00001330668;
ENSE00000894918;ENSE00001280724;ENSE00001326724;ENSE00001179502;ENSE00003591609;
ENSE00000894939;ENSE00001280856;ENSE00001383033;**ENSE00001325501**
```
The last id from the fasta file, `ENSE00001325501`, doesn't exist in the `blat` output (the `.psl` file) and I don't know why. Given that, some keys (from the `seq_length` dictionary), which come from the exons fasta file, aren't the same as the ones in the `psl` file, which are coming from the ids from `blat`.

If you add the missing id to the dictionary key you get ride of the error:

```python
#arr[0] are the ids coming from the psl file
k = arr[0] + ";ENSE00001325501"
seq_length[k]

[out] 5538
```

Edit:I have to add that `blat` seems to add until 30 ids (or 30 "strings" separated by 29 ";") to the `Query id` field,   so any fasta file description line with more than that makes the code fail.

One can put something like this in the `report` rule to check and see which keys are problematic:
```python
.....
elif arr[0] in seq_length.keys():
    print("%s\t%s\t%s\t%s\t%s\t%s" % (arr[0], seq_length[arr[0]], arr[2], arr[3], arr[4], arr[5]), file=f)
else:
    print("This key isn't in seq_length: ", arr[0], end='\n\n')

f.close()
```

**Comment by mw55309** [comment]
Have updated the code with @matrs suggestion

**Comment by pomidorku** [comment]
Hi,

After having problems running the pipeline, I cloned it again with the updated code from 4 days ago.

Now I get the following error:

"SyntaxError in line 140 of /home/ivapps/sm_assemblies/Snakefile:
No rule keywords allowed after run/shell/script/wrapper/cwl in rule report. (Snakefile, line 140)" and the job exits with no results at all.

Does the code need to be fixed?

Regards,

pomidorek
